### ISSUE TITLE
Install fails on Ubuntu with "No such file or directory: '.../ComfyUI/custom_nodes/ComfyUi-iTools\\styles'"

### ISSUE THREAD

**Issue by ArkadyGamza** [MohammadAboulEla/ComfyUI-iTools#3]
```
Traceback (most recent call last):
  File "/home/ark/repos/ComfyUI/nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ark/repos/ComfyUI/custom_nodes/ComfyUI-iTools/__init__.py", line 1, in <module>
    from .iTools_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/ark/repos/ComfyUI/custom_nodes/ComfyUI-iTools/iTools_nodes.py", line 15, in <module>
    from .metadata.shared import styles
  File "/home/ark/repos/ComfyUI/custom_nodes/ComfyUI-iTools/metadata/shared.py", line 88, in <module>
    styles = get_yaml_names(folder_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ark/repos/ComfyUI/custom_nodes/ComfyUI-iTools/metadata/shared.py", line 64, in get_yaml_names
    for file_name in os.listdir(folder_path):
                     ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ark/repos/ComfyUI/custom_nodes/ComfyUi-iTools\\styles'

Cannot import /home/ark/repos/ComfyUI/custom_nodes/ComfyUI-iTools module for custom nodes: [Errno 2] No such file or directory: '/home/ark/repos/ComfyUI/custom_nodes/ComfyUi-iTools\\styles'
```

**Comment by jonny7737** [comment]
Looks like the path is windoze specific. A frequent problem with comfy nodes.

YMMV

**Comment by MohammadAboulEla** [comment]
can you update and tell me if it fixed now.

**Comment by jonny7737** [comment]
After uninstall / reinstall: The issue seems to be resolved.

Thank you.

**Comment by moemmel** [comment]
I just tried to install it and get the following error message - but the directory path exists:

 File "/root/ComfyUI/custom_nodes/ComfyUI-iTools/__init__.py", line 1, in <module>
    from .iTools_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/root/ComfyUI/custom_nodes/ComfyUI-iTools/iTools_nodes.py", line 11, in <module>
    from .metadata.shared import p
  File "/root/ComfyUI/custom_nodes/ComfyUI-iTools/metadata/shared.py", line 88, in <module>
    styles = get_yaml_names(folder_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/custom_nodes/ComfyUI-iTools/metadata/shared.py", line 64, in get_yaml_names
    for file_name in os.listdir(folder_path):
                     ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/ComfyUI/custom_nodes/ComfyUi-iTools/styles'

Cannot import /root/ComfyUI/custom_nodes/ComfyUI-iTools module for custom nodes: [Errno 2] No such file or directory: '/root/ComfyUI/custom_nodes/ComfyUi-iTools/styles'
