### ISSUE TITLE
Cannot handle this data type: (1, 1, 1024, 3), |u1

### ISSUE THREAD

**Issue by TimyTom** [MohammadAboulEla/ComfyUI-iTools#6]
Hi. First of all, thank you for these amazing tools. 

Maybe somone can help with this issue: I keep getting this error as soon as batch_size > 1
"Cannot handle this data type: (1, 1, 1024, 3), |u1"

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-iTools\iTools_nodes.py", line 234, in add_text_overlay
    pil_image = tensor2pil(image)
                ^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-iTools\backend\shared.py", line 93, in tensor2pil
    return Image.fromarray(
           ^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3281, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 1024, 3), |u1

**Comment by MohammadAboulEla** [comment]
would you send me the workflow that cause this error?

**Comment by MohammadAboulEla** [comment]
[
![Screenshot 2024-11-18 003523](https://github.com/user-attachments/assets/e1bb46bb-e28a-4f76-8db0-fedd4c9df32b)
](url)
you have to use Image batch to image list node from [Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack)

**Comment by TimyTom** [comment]
Hi. Thank you for following up, that is actually pretty amazing. And sorry
for answering this late, I wasn't near my PC.

So: attached you find a basic workflow. The error occurs as soon as you
change the batch size to anything > 1.

Please let me know if it's something on my end I'm doing wrong. Thank you.

Tom.

**Comment by MohammadAboulEla** [comment]
@TimyTom Unfortunately, this functionality can't currently be handled directly in the code, as it is a limitation of ComfyUI. To address this, you'll need to add an additional node to convert the image batch into an image list. You can find the required node in the [Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack). Simply install the pack and insert the node before mine, as shown in this example image 
[
![Screenshot 2024-11-18 003523](https://github.com/user-attachments/assets/e1bb46bb-e28a-4f76-8db0-fedd4c9df32b)
](url)
